### ISSUE TITLE
ldaps binding issue

### ISSUE THREAD

**Issue by venkataklagisetty** [spring-projects/spring-ldap#742]
Hi
My application connects and creates users in ldap.
I connect to ldap using ldaps with port 636.
This was working good until spring boot 2.7.x and now with spring boot 3.0.3 and Java 17 it started throwing 
"simple bind failed: <myldap server >:636".

When I tried connecting to with ldap and 389 ( for fetch operations) it connected but keep on failing with ldaps 636.

I tried using below hint as well. still it dint work ( tried with and without native plugin)
public class MyRuntimeHints implements RuntimeHintsRegistrar {

    @Override
    public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
        hints.reflection().registerType(TypeReference.of("javax.net.ssl.SSLSocketFactory"), builder -> builder.withMembers(MemberCategory.INVOKE_PUBLIC_METHODS));
    }
}

Please help me with this

**Comment by venkataklagisetty** [comment]
Caused by: javax.naming.CommunicationException: simple bind failed: <MY ldap server>:636 [Root exception is java.net.SocketException: Connection or outbound has closed]

**Comment by venkataklagisetty** [comment]
Sorry, It was local certificate issue.
Issue got resolved at my end, It worked without Hint  as well

**Comment by alvinwanda** [comment]
@venkataklagisetty, could you explain exactly how you fixed this? having a highly similar issue
importing ldap certificates into cacerts did not solve this
